components/Template.tsx
components/bootstrap.ts
components/layout/Markdown.tsx

<i>Re-opening #11. I hadn't noticed that the bootstrap.ts script wasn't being loaded previously which caused the syntax highlighting to break.</i>
We're currently shipping the entire framer.data.js JSON blob up to the client for no reason. This was due to the components/index.ts file exporting all components including dynamic ones. Monobase then needs to include the index.ts file in the build.
I've now pulled out the dynamic exports into their own subdirectory under components/layout/dynamic so they're no longer included in the components/index.ts files. This reduces the JavaScript bundle by half. I've also remove the contributing images as they're no longer used.

Move dynamic components into subdirectory (Again)

---

components/layout/Sidebar.tsx

We now pull in the "framer" package version from the installed build and display that on the site with minor formatting.

Use the version of the current Framer package

---

api/linkify.ts
components/documentation/APIClass.tsx
components/documentation/APIEnum.tsx
components/documentation/APIFunction.tsx
components/documentation/APIInterface.tsx
components/documentation/APIMethod.tsx
components/documentation/APINamespace.tsx
components/documentation/APIProperty.tsx
components/documentation/APIReactComponent.tsx
components/documentation/APIVariable.tsx
components/layout/Permalink.tsx
components/layout/Ref.tsx

These use the underlying model id so we needed to pass this into `<Permalink>` as well as the new url hash string.

Fix broken `<Ref>` links

---

pages/index.mdx

The function now takes varadic arguments instead of an array. It also now accepts an index argument so cannot be passed directly to an event handler.

Fix useCycle() examples

---

pages/index.mdx
pages/tutorial.mdx

I found some typo in pages/index.mdx("draggble", it should be "draggable") and in pages/tutorial.mdx("postion", it should be "position")

Fix typo in pages/index.mdx & pages/tutorial.mdx

---

pages/utilities.mdx

This PR:
- Fixes up examples that still referencing the hook's arguments as an array.
- Adjusts the two examples to better highlight the specific value option.
- Standardizes the two values returned from `useCycle` as `current` and `cycle`.
- Standardizes the language around what is inside of a `useCycle` call. (Changes "items" to "values").

Updates useCycle examples

---

components/Navigation.tsx
pages/assets.mdx

This adds a new page under /api/assets that documents the `url()` helper function. Due to this file not being part of the library I created the model manually to ensure the formatting is the same, but it might be easier for maintenance to just write this one out with plain markdown.

Add new docs for the url() helper function

---

api/TSDocReactEmitter.ts
api/__tests__/__snapshots__/TSDocReactEmitter.test.ts.snap
components/RawScript.tsx
components/documentation/APIEnum.tsx
components/documentation/APIFunction.tsx
components/documentation/APIInterface.tsx
components/documentation/APIMethod.tsx
components/documentation/APINamespace.tsx
components/documentation/APIOverview.tsx
components/documentation/APIProperty.tsx
components/documentation/APIReactComponent.tsx
components/documentation/APISummary.tsx
components/documentation/APIVariable.tsx
components/documentation/helpers.ts
components/documentation/types.ts
components/layout/Permalink.tsx
package.json
pages/render-target.mdx
tsconfig.json
yarn.lock

This allows highlighting of specific rows within a component example in the same way we do with fenced code blocks in MDX files.
In mdx we would do the following to highlight the middle row:
```jsx highlight(2)
function MyComponent() {
return <Frame size={“100%”} />
}
``` 
To do this for an API component we would do the following:
<APIFunction name=“Color.toRGBString()” highlight=“2” />
Should the API @remarks block contain multiple code blocks we’ll need to pass an array instead of a single string.
<APIFunction name=“Color.toRGBString()” highlight={[“”, “2”, “1-3"]} />
_NOTE: A “falsy” value will omit the highlight block altogether for that code block_

Add highlight prop to API components

---

pages/assets.mdx

The result of the `url()` function can change over time. As a result we don’t want values used in property controls or cached anywhere. So I’ve included a paragraph explaining this and updated the documentation with an example.

Improve URL documentation to avoid caching gotchas

---

.gitignore
Makefile
components/Changelog.tsx
components/Template.tsx
pages/404.tsx

This takes the CHANGELOG.md file from the current “framer” release in node_modules and embeds it under the framer.com/api/changelog url. The pages/changelog.mdx is generated for each call to `make build` or `make serve`.

Add changelog page to API docs

---

components/documentation/APIOverview.tsx
components/highlighter.ts
pages/assets.mdx
pages/examples.mdx
pages/frame.mdx
pages/motion/animate-presence.mdx
pages/motion/examples.mdx
pages/render-target.mdx
pages/tutorial.mdx
pages/utilities.mdx

We have very noisy log output because we were abusing the markdown `metastring` to pass a “highlight” string through to the generated HTML and MDX was unable to parse the unusual strings as prop names. It turns out that MDX supports [passing props](https://mdxjs.com/guides/syntax-highlighting#syntax-highlighting) through to the code blocks for use in custom renderers. Unfortunately we don’t yet support passing a custom `MDXProvider` object to Monobase, however these props are still added to the default HTML as strings.
So:
```tsx highlight=12-30
... some code ...
``` 
Becomes
```
<pre lang="jsx" highlight="12-30">
<code>...</code>
</pre>
```
So we abuse this and extract the string from the attribute in the highlighter module and do the highlighting as before. The JSX component stays the …

Migrate code highlight feature to use “Props” API

---

components/layout/Markdown.tsx
package.json
yarn.lock

The new shared compiler instance speeds up the build time by ~20 seconds.
**Fixes**
MDX now creates a MDXCreateElement instance for all imported tags rather than just passing the component directly. So we've updated the isAPIElement() helper to check for this condition as well as
React elements.

Upgrade Monobase

---

.circleci/config.yml
test/stylecheck.ts

Currently this only checks for JSX string props that should be using interpolation as this often catches new React users out. This won't fail the build, but will hopefully help us track down inconsistencies.
Could be extended in future to actually validate the examples themselves.

Check code examples for consistent JSX formatting

---

components/layout/Markdown.tsx

The code added to apply padding to the Motion examples was incorrectly applying padding to all code blocks. This change fixes this as well as better detecting the ExampleCode and ExampleDemo blocks.

Fix layout of Motion examples

---

pages/animate-presence.mdx
pages/frame.mdx
pages/motion/animate-presence.mdx

Needs upgrade to latest `motion`. Inline docs here: https://github.com/framer/motion/pull/208

Adding positionTransition and AnimatePresence to the Library docs

---

api/TSDocReactEmitter.ts
package.json
yarn.lock

Fixes GitHub Security Alerts for lodash, remarkable and underscore.string.
Tested that the `data`, `build`, and `watch` commands still work correctly. 
The following have been updated to the "latest" version:
```
Package                        Current    Wanted     Latest     Package Type    URL                                                                     
@types/cheerio                 0.22.11    0.22.13    0.22.13    devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/classnames              2.2.7      2.2.9      2.2.9      devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/jest                    24.0.11    24.0.17    24.0.17    devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git
@types/prismjs …
```

Upgrade dependencies

---

pages/tutorial.mdx

The service should be called "CodeSandbox".

Fix confusing reference "Sandbox.io" in tutorial

---

pages/scroll.mdx

Update the example as we removed `size` from ScrollProps and PageProps: https://github.com/framer/company/issues/12378
related: https://github.com/framer/company/issues/13410

Remove "size" usage in t example on Scroll page

---

components/Navigation.tsx

cc @krijnrijshouwer 
Now that the React eBook is published, we should point people there instead of the old Paper doc. I used the full link path here because I'm not sure how a relative path would work in this Navigation component.
---
@aron I added you as a reviewer only because I see you are the most active in this repo. Let me know if someone else is a better reviewer for changes like this or what the process for PR's is! Thanks in advance :)

Replace `ES6 and React` link

---

pages/assets.mdx

For Framer Web, we won't serve the full project, only the assets folder. Make sure the documentation reflects that.

Prepare documentation for Framer Web limitations.

---

pages/animation.mdx
pages/examples.mdx
pages/frame.mdx
pages/motion/animation.mdx
pages/motion/component.mdx
pages/scroll.mdx

docs: grammatical errors and typos fix

---

pages/property-controls.mdx

Adding in `ControlType.EventHandler` and `ControlType.Transition` to the property controls section under the api docs. Added a Beta flag with a Callout explaining where and when you can use these features.

Add EventHandler and Transition to Property Controls docs

---

components/Navigation.tsx
pages/motion/animate-shared-layout.mdx
pages/motion/animation.mdx

Provides documentation for the new auto `animate` prop and `AnimateSharedLayout`. I think the Magic Move connection can be made in the Handoff guide once these are in master.

Adding Magic Motion documentation

---

pages/motion/animate-shared-layout.mdx

Hey!
Just wanted to let you folks know that it's possible to hide the devtools when unnecessary with `hidedevtools=1` for a more minimal look.
The example for `AnimateSharedLayout ` doesn't look like it needs it : https://www.framer.com/api/motion/animate-shared-layout

Hide devtools in codesandbox embed

---

pages/property-controls.mdx

Removing the beta tags for EventHandler and Transition property controls.

Remove beta tags on new propertyControls

---

pages/motion/examples.mdx

This just adds a small note about the `exitBeforeEnter` prop which I had to do a bunch of Googling for to realize existed and would solve my problem. I think this is probably a fairly common use case to need to have pages/screen slide in and out.

Add note about `exitBeforeEnter` prop to Exit Animations

---

pages/motion/animate-presence.mdx
pages/motion/utilities.mdx

Following up on [framer/motion #753](https://github.com/framer/motion/pull/753#issue-480957865).
Adds documentation for `useIsPresent`.

Add documentation for useIsPresent

---

pages/motion/gestures.mdx
pages/navigation.mdx
pages/page.mdx

This adds two example project files to:
/api/navigation/#transitions
/api/motion/gestures/#draggableprops.dragcontrols
And also fixes a typo

Add examples to framer/navigation and motion/gestures

---

pages/motion/component.mdx

I just tried it and the units are part of the variables.

fix: typo in transformTemplate

---

CONTRIBUTING.md
README.md
components/Template.tsx
components/tutorial/SliderComplete.tsx
components/tutorial/SliderData.tsx
components/tutorial/SliderStarter.tsx
pages/tutorial.mdx

We are moving away from serving unmanaged files on the `framer.com` domain, part of which is migrateing from `static.framer.com` to `misc.framerstatic.com`. The old links will keep on working through a 302 redirect, but let's update all the links.
Ref: https://github.com/framer/company/issues/20653

Update all 'static.framer.com' links
