framer/api-docs

pages/property-controls.mdx

Double 'the'

---

components/GoogleTag.tsx

Update the GA tracking script & verified it’s now working via the admin.

Update Google Analytics script

---

components/Navigation.tsx
pages/motion/examples.mdx
pages/motion/migrate-from-pose.mdx

Closes https://github.com/framer/motion/issues/183

adding pose migration guide

---

package.json
yarn.lock

The Monobase context is now available in the client, I have a feeling we may have used this in the past to determine whether we were on the client or server so this needs a bit of QA just to make sure things load as expected.

Bump Monobase for faster build!

---

pages/motion/migrate-from-pose.mdx

Some small typos I noticed while going through the upgrade docs :)

migrate-from-pose typo fixes

---

components/examples/motion/PositionTransition.tsx
pages/animate-presence.mdx
pages/animation.mdx
pages/frame.mdx
pages/motion/animate-presence.mdx
pages/motion/component.mdx
pages/motion/examples.mdx

- `onAnimationStart`
- `exitBeforeEnter`
- Adding "More" section for examples with links to external sandboxes

New Motion and Library content

---

components/404.tsx
components/Template.tsx
components/documentation/ReleaseBadge.tsx
components/examples/motion/MotionValueSVG.tsx
components/index.tsx
components/layout/Grid.tsx
components/layout/Header.tsx
components/layout/InlineCallToAction.tsx
components/layout/Markdown.tsx
components/layout/Menu.tsx
components/layout/Permalink.tsx
components/layout/Sidebar.tsx
components/layout/dynamic/SubNavigation.tsx
netlify.toml
pages/404.tsx
pages/motion/404.tsx
pages/motion/examples.mdx

- Use API specific accent colors, fixes framer/company#13933.
- Update API switch, fixes framer/company#13932.

Differentiate Library and Motion

---

pages/property-controls.mdx

Separates these two out and adds mention of defaultProps.

Updates Intro / Adding Property Controls

---

package.json
pages/motion/component.mdx
yarn.lock

Fixes https://github.com/framer/motion/issues/343

Adding inherit prop to docs

---

CONTRIBUTING.md
README.md
components/tutorial/SliderStarter.tsx
pages/canvas-components.mdx
pages/index.mdx
pages/tutorial.mdx

Fixed a few non-secure HTTP URLs.

Upgrade non-secure HTTP URLs to HTTPS

---

pages/motion/motionvalue.mdx

This fixes the duplicated documentation for the useTransform() function.

Update index of overloaded method for useTransform

---

pages/motion/gestures.mdx

Fixed double word

---

components/Navigation.tsx
package.json
pages/motion/guide-accessibility.mdx
pages/motion/utilities.mdx
pages/utilities.mdx
yarn.lock

Docs for https://github.com/framer/motion/pull/407
I think I'm going to simplify that API to start with only the `useReducedMotion` hook hence only its inclusion here.

Adding accessibility guide

---

pages/motion/component.mdx

fixed typo

---

package.json
yarn.lock

Just to change the version number in the top

Update Framer Library to 1.2.2

---

components/examples/motion/ViewportScroll.tsx
static/styles/highlight.css

Prevents showing superfluous scrollbars.

Fix: Unforce code blocks overflow

---

pages/motion/animate-shared-layout.mdx

My thought was 'inherit', but if that's not exactly the right word, at least I brought it to attention.
Thanks for the rad product. This is my first PR on someone else's work, my apologies if the etiquette is a bit off.

Missing word on line 153

---

pages/motion/migrate-from-pose.mdx

Since v2.0 the prop layoutTransition is replaced wit layout prop

Replace layoutTransition with layout

---

pages/help.mdx
pages/motion/help.mdx

Fixes to your suggested copy + the button style, which had to be wrapped in a div or it became messed up in non-mobile

Fix copy and buttons

---

pages/animation-deprecated.mdx
pages/frame-deprecated.mdx

Fixes https://github.com/framer/site/issues/233.

Fix: Heading hierarchy

---

components/documentation/APIReactComponent.tsx
pages/navigation.mdx

Requires https://github.com/framer/FramerStudio/pull/7916 to land first

Add automatic layout

---

pages/motion/examples.mdx

Corrected a minor spelling error!

Fixed typo in pages/motion/examples.mdx

---

pages/motion/motion-config.mdx

The closing tag `<MotionConfig>`should be closed by a `</MotionConfig>` instead of the `</AnimatePresence>`.

Fix wrong closing tag in the example

---

pages/motion/guide-upgrade.mdx

Fix hierarchy-level of subheadline

---

pages/motion/lazy-motion.mdx

* closing tag
* link to reduce bundle size article

Fix some typos in lazy-motion.mdx

---

pages/motion/examples.mdx

The onClick method given to the Toggle component was not using the updater function method to update the state based on previous values.

Fix setting the state in variants section in motion/examples.mdx

---

model/searchify.ts
package.json
utils/isProduction.ts
yarn.lock

Due to a Playwright bug (afaik), search indexing has been stuck for almost a month, this PR attempts to fix that.

Fix: Search indexing
